export const hiraganaWords = {
    こんにちは: { romaji: 'konnichiwa', english: 'hello' },
    おはよう: { romaji: 'ohayou', english: 'good morning' },
    こんばんは: { romaji: 'konbanwa', english: 'good evening' },
    さようなら: { romaji: 'sayounara', english: 'goodbye' },
    ありがとう: { romaji: 'arigatou', english: 'thank you' },
    はい: { romaji: 'hai', english: 'yes' },
    いいえ: { romaji: 'iie', english: 'no' },
    すみません: { romaji: 'sumimasen', english: 'excuse me / sorry' },
    おねがいします: { romaji: 'onegaishimasu', english: 'please' },
    ごめんなさい: { romaji: 'gomennasai', english: 'I’m sorry' },
    わたし: { romaji: 'watashi', english: 'I / me' },
    あなた: { romaji: 'anata', english: 'you' },
    かれ: { romaji: 'kare', english: 'he' },
    かのじょ: { romaji: 'kanojo', english: 'she' },
    ともだち: { romaji: 'tomodachi', english: 'friend' },
    いち: { romaji: 'ichi', english: 'one' },
    に: { romaji: 'ni', english: 'two' },
    さん: { romaji: 'san', english: 'three' },
    よん: { romaji: 'yon', english: 'four' },
    ご: { romaji: 'go', english: 'five' },
    やま: { romaji: 'yama', english: 'mountain' },
    かわ: { romaji: 'kawa', english: 'river' },
    はな: { romaji: 'hana', english: 'flower' },
    そら: { romaji: 'sora', english: 'sky' },
    みず: { romaji: 'mizu', english: 'water' },
    ごはん: { romaji: 'gohan', english: 'rice / meal' },
    みそしる: { romaji: 'misoshiru', english: 'miso soup' },
    さかな: { romaji: 'sakana', english: 'fish' },
    にく: { romaji: 'niku', english: 'meat' },
    やさい: { romaji: 'yasai', english: 'vegetables' },
    きょう: { romaji: 'kyou', english: 'today' },
    あした: { romaji: 'ashita', english: 'tomorrow' },
    きのう: { romaji: 'kinou', english: 'yesterday' },
    とき: { romaji: 'toki', english: 'time' },
    じかん: { romaji: 'jikan', english: 'hour / time' },
    がっこう: { romaji: 'gakkou', english: 'school' },
    せんせい: { romaji: 'sensei', english: 'teacher' },
    がくせい: { romaji: 'gakusei', english: 'student' },
    ほん: { romaji: 'hon', english: 'book' },
    えんぴつ: { romaji: 'enpitsu', english: 'pencil' },
    いえ: { romaji: 'ie', english: 'house' },
    みせ: { romaji: 'mise', english: 'shop' },
    まち: { romaji: 'machi', english: 'town' },
    えき: { romaji: 'eki', english: 'station' },
    くるま: { romaji: 'kuruma', english: 'car' },
    たべる: { romaji: 'taberu', english: 'to eat' },
    のむ: { romaji: 'nomu', english: 'to drink' },
    みる: { romaji: 'miru', english: 'to see / watch' },
    いく: { romaji: 'iku', english: 'to go' },
    くる: { romaji: 'kuru', english: 'to come' },
    ちち: { romaji: 'chichi', english: 'father' },
    はは: { romaji: 'haha', english: 'mother' },
    あに: { romaji: 'ani', english: 'older brother' },
    あね: { romaji: 'ane', english: 'older sister' },
    いもうと: { romaji: 'imouto', english: 'younger sister' }
};